service: myserverlessproject
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myServerlessprojectUpload-1231234