service: myserverlessproject
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-s3-sync
  - serverless-offline

package: 
  individually: true

custom:
  tableName: player-points
  s3Sync:
    - bucketName: server1essprojectupload-22321321321
      localDir: UploadData
  

  functions:
    getUser:
        handler: lambdas/getUser.handler
        events:
          - http:
                path: get-user/{ID}
                method: GET
                cors: true

  helloWorld:
      handler: handler.hello
      events:
        - http:
            path: helloWorld
            method: GET

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: server1essprojectupload-22321321321
    
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        
        
