service: send-SMS
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:SetSMSAttributes
        - sns:Publish
      Resource: '*'

functions:
    sendSMS:
      handler: lambdas/endpoints/sendSMS.handler
      events:
        - http:
            path: send-sms
            method: POST
            cors: true