service: step-functions
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
        - ses:*
      Resource: '*'
  apiGateway:
    apiKeys:
      - free:
        - MyFreeApiKey
      - paid:
        - MyPaidApiKey
        - user2PaidApiKey
    usagePlan:
      - free:
          quota:
            limit: 1000
            period: MONTH
          throttle:
            rateLimit: 5
            burstLimit: 20
      - paid:
          quota:
            limit: 1000
            period: MONTH
          throttle:
            burstLimit: 20
            rateLimit: 5

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-stepfunctions

package: 
  individually: true
