service: amazoncomprehend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
    analyseText:
      handler: lambdas/endpoints/analyse.handler
      events:
        - http:
            path: /analiseText
            cors: true
